### ISSUE TITLE
json统一返回状态码200，怎么修改才合适呢？

### ISSUE THREAD

**Issue by mydzoo** [wxlite-plus/mp-req#2]
因为后端json统一返回状态码200，json中包含 code, message, data, time 四个参数，code不等于0则代表错误代码，message代表错误消息。

怎么调整代码呢？看了看封装的是请求头的statusCode

**Comment by mydzoo** [comment]
然后就是每个页面都需要const req = require('../../req/index.js'); 一下，怎么调整才能全局通用呢？

比如写在app.js里面，然后page页面的js直接 app.req.user.getMyInfo()?? 技术能力有限，还望指点

**Comment by Jack-Lo** [comment]
json的code属于业务层面的了，建议在业务代码里处理，全局统一处理可能会导致一些难以处理的情况，建议如下方式处理：
```javascript
req.user.getMyInfo()
  .then((res) => {
    if (res.code !== 0) {
      // 成功
    } else {
      // 失败
    }
  })
  .catch((err) => {
    // 失败
  });
```

**Comment by Jack-Lo** [comment]
建议是按需引用，也就是每次都手动`const req = require('../../req/index.js');`，这样的开发方式更透明，读者更容易理解；
如果想要实现全局访问的话，那就要考虑劫持Page函数的方式了，可以参考[ez-wxlite的实现](https://github.com/wxlite-plus/ez-wxlite/blob/master/client/framework/page.js)。

**Comment by mydzoo** [comment]
非常感谢，我明白了。确实是可以这样处理。但是错误返回的消息呢？我看内置的是msg，而我返回的是message 这个怎么处理 或者 传参呢？ 还有这个 statusCode 问题。如何将我的这种json返回格式来显示在showModal里面呢？ 目前尝试了修改err.js，msg改成message是可以的。但是我知道这样并不合理。

**Comment by Jack-Lo** [comment]
err.js其实是req的一个插件，你可以自由修改，没问题的
