### ISSUE TITLE
所有的接口都需要登录？

### ISSUE THREAD

**Issue by songlen** [wxlite-plus/mp-req#4]
看了好几遍文档，这是默认所有的接口都需要登录吗？只要检测到没有 sessionId 都让去登录是吗？

**Comment by Jack-Lo** [comment]
> 看了好几遍文档，这是默认所有的接口都需要登录吗？只要检测到没有 sessionId 都让去登录是吗？

只要监测到本地没有sessionId都会先去登录，默认是需要登录的，同时也支持不登录设置[keepLogin](https://github.com/wxlite-plus/mp-req/blob/98d0a2862554160708d47b04d1c3cc818c603e2e/prototype.js#L165)
