### ISSUE TITLE
请问后端如何判断session过期？

### ISSUE THREAD

**Issue by killerlayup** [wxlite-plus/mp-req#5]
`只有在需要跟微信（后端）接口打交道的时候，才需要有效的session_key，那么后端肯定知道什么时候过期了，因为微信后端会告诉我们，所以我们把过期的判断交给后端，只要后端被告知过期了`

这里有一点没看明白，请问后端如何判断session过期？感谢答疑

**Comment by Jack-Lo** [comment]
> 

首先，session_key用于与微信服务交互，当我们的业务需要跟微信打交道的时候，比如推送模板消息、比如发起支付，这时候后端就需要将session_key作为入参传给微信服务，如果此时session_key过期了，那么微信服务会就会告诉我们后端特定的信息让我们知道过期了，那么后端就会返回特定的信息告诉前端过期了，那么前端就会重新去调用wx.login再去登录一边，以换取新的session_key，然后重复上个未完成的业务
